"""empty message

Revision ID: 1a4e54b6bc94
Revises: 23c0082b6ba
Create Date: 2014-11-29 01:06:14.308827

"""

# revision identifiers, used by Alembic.
revision = '1a4e54b6bc94'
down_revision = '23c0082b6ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_assignment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('password', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'password')
    op.drop_column(u'user', 'created_at')
    op.drop_column(u'user', 'active')
    op.drop_table('role_assignment')
    op.drop_table('role')
    ### end Alembic commands ###
