"""empty message

Revision ID: 23c0082b6ba
Revises: 363fb8ef8ebc
Create Date: 2014-11-24 23:26:03.297013

"""

# revision identifiers, used by Alembic.
revision = '23c0082b6ba'
down_revision = '363fb8ef8ebc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    ### end Alembic commands ###
