"""empty message

Revision ID: 76961c69ca3
Revises: 1a4e54b6bc94
Create Date: 2014-11-29 02:21:40.048478

"""

# revision identifiers, used by Alembic.
revision = '76961c69ca3'
down_revision = '1a4e54b6bc94'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    ### end Alembic commands ###
